### PR TITLE
Compatibility with Sprockets 2.2 - 2.8

### PR DESCRIPTION
**Pull request by jamesarosen**
- add some basic tests
- add [Appraisals](https://github.com/thoughtbot/appraisal) for each minor version of Sprockets 2
- fix a compatibility issue with `logical_path` on Sprocket 2.3+

This replaces #15 (and expands compatibility).

### CODE REVIEW

**Comment by jamesarosen** [comment]
@maccman this is somewhat time critical because Rails 2.3.10 [patches a SQL injection attack](https://groups.google.com/forum/?fromgroups=#!topic/rubyonrails-security/DCNTNp_qjFM) and requires Sprockets 2.2.

**Comment by maccman** [comment]
Thanks. Sorry for the delay. @jamesarosen Do you want me to release a new version?

**Comment by jamesarosen** [comment]
That would be fantastic :)

**Comment by maccman** [comment]
Done

**Pull request merged**
