### PR TITLE
rake assets:precompile returned the error 'can't modify immutable index'

### PR DESCRIPTION
**Pull request by nvh**
By using an initializer block, this issue is fixed

### CODE REVIEW

**Comment by nvh** [comment]
The second commit is just a bit of cleaning up. The commit message is pretty self-explanatory

**Comment by maccman** [comment]
The trouble with this fix is that's it's Rails specific. In other words the commonjs.js file is not going to be picked up for situations in which your'e not using Rails. What version of Rails are you seeing this error on?

**Comment by nvh** [comment]
The file is encapsulated by if defined?(Rails), so I don't think that should be a problem.
I agree that commit a26890f maybe is a bit Rails specific, but It's also not a weird place to put the javascript file

I should probably have created a different request for commit a26890f, that one is not essential for the fix of this problem

I'm using Rails 3.2.3

**Comment by subblue** [comment]
I'm seeing this issue with Rails 3.2.3 too.

**Comment by maccman** [comment]
I still can't reproduce this problem :(

**Comment by subblue** [comment]
Maccam, if it helps this is my gemfile from a freshly created Rails app:
https://gist.github.com/2794327

and this is the stack trace when running: rake assets:precompile
https://gist.github.com/2794324

and I've just added the commonjs line at the top of my index.js.coffee file (I'm trying Spine with Rails after seeing your excellent Stylo project!)
#= require sprockets/commonjs

**Comment by maccman** [comment]
@nvh Ah, good - I can reproduce it now. Can you put #a26890f in a different commit and I'll merge this?

**Comment by nvh** [comment]
Sorry for my delay in reaction, thanks for pulling!

**Pull request merged**
