### PR TITLE
can now have a custom namespace in the JS file

### PR DESCRIPTION
**Pull request by bmuller**
Sometimes you don't want to use "require" due to conflicts - this allows you to set:

``` ruby
Sprockets::CommonJS.default_namespace = "this.different_require"
```

so that you can use "different_require" in the javascript too.

### CODE REVIEW

**Comment by bmuller** [comment]
This is a fairly small change - any chance of getting it merged?  Thanks!

**Comment by valverde** [comment]
+1

**Comment by bsheldon** [comment]
+1

**Comment by bmuller** [comment]
Thanks!  Really happy to see this merged!

**Comment by bmuller** [comment]
This wasn't actually merged into what ended up in 0.6!

**Comment by bmuller** [comment]
Though I see it's in master now - any chance of this finally getting released?  Perhaps a new minor version?

**Pull request merged**
